---
- hosts: test
  become: yes
  gather_facts: yes
  tasks:

  - name: gather os specific variables
    include_vars: "{{ item }}"
    with_first_found:
            "vars/{{ ansible_machine }}.yaml"

#  - debug:
#          var: configname

  - block: #Block Ubuntu/Debian

    - name: Add ca-serts
      apt:
          name: ca-certificates
          state: latest
          update_cache: yes

    when: ansible_os_family == "Debian"


  - block: # Centos/RedhHat
    
    - name: Add ca-serts
      yum:
          name: ca-certificates
          state: present

    when: ansible_os_family == "RedHat"

  - name: Create group node_exporter
    group:
        name: node_exporter
        state: present

  - name: Create user node_exporter
    user:
        name: node_exporter
        shell: /bin/false
        group: node_exporter

  - name: Download node_exporter tar from Prometheus github
    unarchive:
        src: "{{ node_exporter_url}}"
        dest: /tmp/  
        remote_src: yes
    when: ansible_machine == "x86_64" 

  - name: Copy node_exporter to bin folder
    copy:
        src: /tmp/{{ node_exporter_filename }}/node_exporter
        dest: /usr/local/bin/
        owner: node_exporter
        group: node_exporter
        mode: '0755'
        remote_src: yes

  - name: Create new systemd config file from template
    template:
        src: "./templates/node_exporter.service.j2"
        dest: "/etc/systemd/system/node_exporter.service"
    notify: "Restart service daemon-reload"


    #  - name: Start service node_exporter
    #    service:
    #        name: "node_exporter"
    #        state: started
    #        enabled: yes
  - name: Restart service node_exporter
    systemd:
        state: started
        daemon_reload: yes
        name: node_exporter
        enabled: yes

  - name: Allow connections on 9100  port
    iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 9100
        jump: ACCEPT
#  - name: Check http metrics page

  - name: Confirm that 200 OK response is returned
    uri:
        url: "http://{{ inventory_hostname }}:9100/metrics"
        status_code: 200
    delegate_to: 127.0.0.1

  handlers:
  - name: Restart service daemon-reload
    service: 
        name: "daemon-reload"
        state: restarted
